//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabelcategory
    {
        internal int cat_status;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabelcategory()
        {
            this.tabelproducts = new HashSet<tabelproduct>();
        }
    
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string cat_image { get; set; }
        public Nullable<int> cat_fk_ad { get; set; }
    
        public virtual tabeladmin tabeladmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabelproduct> tabelproducts { get; set; }
    }
}
